name: test-runner
version: 1.0.0
description: Automated test runner that detects and executes tests in various frameworks

llm:
  model: gpt-4o
  temperature: 0.2
  max_tokens: 3000

tools:
  - name: detect_package_json
    command: [test, -f, package.json]
    parameters: []
    description: Check if package.json exists

  - name: read_package_json
    command: [cat, package.json]
    parameters: []
    description: Read package.json to detect test scripts

  - name: detect_pytest
    command: [bash, -c, "find . -name 'test_*.py' -o -name '*_test.py' | head -5"]
    parameters: []
    description: Find Python test files

  - name: detect_go_tests
    command: [bash, -c, "find . -name '*_test.go' | head -5"]
    parameters: []
    description: Find Go test files

  - name: run_npm_test
    command: [npm, test]
    parameters: []
    description: Run npm test

  - name: run_pytest
    command: [pytest, -v]
    parameters: []

  - name: run_go_test
    command: [go, test, "./..."]
    parameters: []

  - name: run_jest
    command: [npx, jest]
    parameters: []

  - name: run_jest_coverage
    command: [npx, jest, --coverage]
    parameters: []

  - name: run_custom_script
    command: [bash, -c]
    parameters:
      - name: script
        type: string
        description: Custom test command
        inject_as: argument

  - name: check_test_results
    command: [bash, -c, "echo $?"]
    parameters: []
    description: Check last command exit code

  - name: write_results
    command: [tee]
    parameters:
      - name: filename
        type: string
        description: Results filename
        inject_as: argument
      - name: content
        type: string
        description: Test results
        inject_as: stdin

