# Memory Folding Example Agent
# Demonstrates Delta Engine v1.6's context composition with dynamic memory compression
# Uses computed_file source type to generate summaries on-the-fly

name: memory-folding
version: 1.0.0
description: Demonstrates context compression using computed_file generators

llm:
  model: gpt-5-mini              # Fast model for demo purposes
  temperature: 0.7                # Balanced creativity for multi-step tasks
  max_tokens: 4000                # Sufficient for file operations + reasoning

tools:
  # File operations for workspace manipulation (v1.7 Simplified Syntax)
  # These tools allow the agent to persist information across iterations

  - name: write_file
    description: Write content to a file in the workspace
    exec: "tee ${filename}"       # v1.7: Simplified syntax for direct execution
    stdin: content                # Declare 'content' as stdin parameter

  - name: read_file
    description: Read content from a file
    exec: "cat ${filename}"       # v1.7: Single-line tool definition

  - name: list_files
    description: List files in a directory (detailed format)
    exec: "ls -la ${directory}"   # v1.7: Automatic parameter inference
