name: hello-world
version: 1.0.0
description: A simple hello world agent to demonstrate basic Delta Engine capabilities

llm:
  model: gpt-4o
  temperature: 0.7
  max_tokens: 1000

tools:
  - name: print_message
    command: [echo]
    parameters:
      - name: message
        type: string
        description: Message to print
        inject_as: argument

  - name: create_file
    command: [touch]
    parameters:
      - name: filename
        type: string
        description: Name of file to create
        inject_as: argument

  - name: write_to_file
    command: [tee]
    parameters:
      - name: filename
        type: string
        description: File to write to
        inject_as: argument
      - name: content
        type: string
        description: Content to write
        inject_as: stdin

  - name: list_files
    command: [ls, -la]
    parameters: []

  - name: show_date
    command: [date]
    parameters: []