name: hello-world
version: 1.0.0
description: A simple hello world agent demonstrating Delta Engine's Three Pillars

# LLM Configuration
llm:
  model: gpt-5-mini              # Fast and capable model for simple tasks
  temperature: 0.7               # Balanced creativity (0=deterministic, 1=creative)
  max_tokens: 2000               # Enough for educational, verbose responses

# Tools - Everything is a Command (v1.7 Simplified Syntax)
# Each tool uses exec: mode for direct, safe command execution

tools:
  # Print a message to stdout
  - name: print_message
    description: Print a message to standard output
    exec: "echo ${message}"      # v1.7: Simplified syntax for direct execution

  # Create an empty file
  - name: create_file
    description: Create an empty file (idempotent - won't fail if exists)
    exec: "touch ${filename}"    # v1.7: Single-line tool definition

  # Write content to a file
  - name: write_to_file
    description: Write or overwrite content to a file
    exec: "tee ${filename}"      # v1.7: Automatic parameter inference
    stdin: content               # Declare 'content' as stdin parameter

  # List files in current directory
  - name: list_files
    description: List all files and directories with details
    exec: "ls -la"               # v1.7: No parameters needed, simple command

  # Show current date and time
  - name: show_date
    description: Display current system date and time
    exec: "date"                 # v1.7: Minimal syntax for parameterless tools

# Maximum iterations before automatic stop
max_iterations: 30
