name: python-repl
version: 1.0.0
description: Agent with persistent Python REPL session (v1.5 simplified)

llm:
  model: gpt-5-mini
  temperature: 0.7
  max_tokens: 2000

tools:
  # Start Python REPL
  - name: python_start
    description: "Start a persistent Python interactive session (REPL). Returns a session_id."
    command: [delta-sessions, start, python3]
    parameters: []

  # Execute Python code
  - name: python_exec
    description: |
      Execute Python code in the REPL session.
      Returns complete output immediately (stdout, stderr, exit_code).
      Variables and imports persist across executions.
    command: [delta-sessions, exec]
    parameters:
      - name: session_id
        type: string
        description: "Session ID from python_start"
        inject_as: argument
      - name: code
        type: string
        description: "Python code to execute (can be multi-line)"
        inject_as: stdin

  # End session
  - name: python_end
    description: "Terminate the Python REPL session"
    command: [delta-sessions, end]
    parameters:
      - name: session_id
        type: string
        description: "Session ID"
        inject_as: argument
