name: doc-generator
version: 1.0.0
description: Generates comprehensive documentation for codebases

llm:
  model: gpt-4o
  temperature: 0.4
  max_tokens: 4000

tools:
  - name: find_source_files
    command: [bash, -c, "find . -type f \\( -name '*.js' -o -name '*.ts' -o -name '*.py' -o -name '*.go' \\) | grep -v node_modules | grep -v .git | head -20"]
    parameters: []

  - name: read_file
    command: [cat]
    parameters:
      - name: filepath
        type: string
        description: File to read
        inject_as: argument

  - name: analyze_structure
    command: [bash, -c, "tree -L 3 -I 'node_modules|.git' || find . -type d -not -path '*/\\.*' | head -20"]
    parameters: []
    description: Show project structure

  - name: extract_functions
    command: [grep, -n, "function\\|def\\|func"]
    parameters:
      - name: file
        type: string
        description: File to search in
        inject_as: argument

  - name: count_files
    command: [bash, -c, "find . -type f \\( -name '*.js' -o -name '*.ts' -o -name '*.py' -o -name '*.go' \\) | wc -l"]
    parameters: []

  - name: create_markdown
    command: [tee]
    parameters:
      - name: filename
        type: string
        description: Documentation filename
        inject_as: argument
      - name: content
        type: string
        description: Documentation content
        inject_as: stdin

  - name: create_readme
    command: [tee, README.md]
    parameters:
      - name: content
        type: string
        description: README content
        inject_as: stdin

  - name: check_existing_docs
    command: [bash, -c, "ls -la *.md 2>/dev/null || echo 'No markdown files found'"]
    parameters: []
    description: Check for existing documentation

