name: git-analyzer
version: 1.0.0
description: Analyzes git repositories and provides insights about code changes

llm:
  model: gpt-4o
  temperature: 0.3
  max_tokens: 2000

tools:
  - name: git_status
    command: [git, status, --short]
    parameters: []
    description: Check current git status

  - name: git_log
    command: [git, log, --pretty=oneline, -n, "10"]
    parameters: []

  - name: git_diff
    command: [git, diff]
    parameters:
      - name: file
        type: string
        description: File to diff (optional)
        inject_as: argument
        required: false

  - name: git_branch
    command: [git, branch, -a]
    parameters: []
    description: List all branches

  - name: count_lines
    command: [bash, -c, "find . -type f \\( -name '*.js' -o -name '*.ts' -o -name '*.py' \\) | xargs wc -l | tail -1"]
    parameters: []

  - name: find_large_files
    command: [bash, -c, "find . -type f -size +1M -exec ls -lh {} \\; | awk '{print $9, $5}'"]
    parameters: []

  - name: git_contributors
    command: [git, shortlog, -sn, --all]
    parameters: []
    description: List contributors by commit count

  - name: write_report
    command: [tee]
    parameters:
      - name: filename
        type: string
        description: Report filename
        inject_as: argument
      - name: content
        type: string
        description: Report content
        inject_as: stdin