name: Version Consistency Check

on:
  pull_request:
    paths:
      - 'package.json'
      - 'CHANGELOG.md'
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  check-version-consistency:
    name: Validate Version Consistency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run version consistency check
        run: |
          chmod +x ./scripts/check-version-consistency.sh
          ./scripts/check-version-consistency.sh

      - name: Check CHANGELOG format
        run: |
          echo "Validating CHANGELOG.md format..."

          # Check if CHANGELOG has proper version format
          if ! grep -q "^## \[.*\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" CHANGELOG.md; then
            echo "❌ CHANGELOG.md version entries must follow format: ## [X.Y.Z] - YYYY-MM-DD"
            exit 1
          fi

          echo "✅ CHANGELOG.md format is valid"

      - name: Verify package.json version format
        run: |
          echo "Validating package.json version format..."

          VERSION=$(jq -r '.version' package.json)

          # Check semantic versioning format
          if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "❌ package.json version must follow semantic versioning (X.Y.Z)"
            echo "   Current version: $VERSION"
            exit 1
          fi

          echo "✅ package.json version format is valid: $VERSION"

      - name: Summary
        if: success()
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "✅ All version consistency checks passed!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
